Tonnie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Yucca.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Yucca/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='Yucca'

urlpatterns=[
    path('', views.index, name='index'),
    path('(?P<album_id>[0-9]+)/', views.details, name='details'),
    path('add-album', views.add_album, name='add_album'),
    path('(?P<album_id>[0-9]+)/add-song)', views.add_song,name='add-song'),
    path('(?P<album_id>[0-9]+)/delete-album', views.delete_album,name='delete-album'),
    path('signup', views.signup,name='signup'),
   # path('login', auth_views.LoginView.as_view(),name='login'),
    #path('logout',auth_views.LogoutView.as_view(),name='logout'),
    path('login',views.login_user,name='login'),
    path('logout', views.logout_user, name='logout'),
    path('(?P<album_id>[0-9]+)/update-album', views.update_album, name='update-album'),
    path('(?P<album_id>[0-9]+)/delete-song/(?P<song_id>[0-9]+)', views.delete_song, name='delete-song'),
    path('(?P<album_id>[0-9]+)/update-song/(?P<song_id>[0-9]+)', views.update_song, name='update-song')

]

Yucca/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
GENRE=(
    ('Unknown', 'unknown'),
    ('Rap','rap'),
    ('Riddim','riddim'),
    ('RnB','rnb'),
    ('Local','local'),
    ('Pop','pop'),
    ('House','house'),
)

class Album(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    name=models.CharField(max_length=40)
    artist=models.CharField(max_length=40)
    year=models.CharField(max_length=4)
    cover=models.ImageField()
    genre=models.CharField(choices=GENRE, max_length=30,default='unknown')

    def __str__(self):
        return self.name

class Song(models.Model):
    album=models.ForeignKey(Album, on_delete=models.CASCADE)
    name=models.CharField(max_length=40)
    audio=models.FileField()

    def __str__(self):
        return self.name

Yucca/forms.py
from django import forms
from .models import Album, Song
from django.contrib.auth.models import User
class AlbumForm(forms.ModelForm):

    class Meta:
        model= Album
        fields=['name', 'artist', 'cover', 'genre', 'year']

class SongForm(forms.ModelForm):
    class Meta:
        model=Song
        fields=['name','audio']


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['email','username','password']

Yucca/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Album,Song
from .forms import AlbumForm, SongForm, UserForm
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required(login_url='Yucca:login')
def index(request):
    albums=Album.objects.filter(user=request.user)
    context={
        'albums':albums
    }
    return render(request,'Yucca/index.html', context)


def details(request, album_id):
    album=get_object_or_404(Album, pk=album_id)
    return render(request,'Yucca/details.html', {'album': album})

@login_required(login_url='Yucca:login')
def add_album (request):
    form=AlbumForm(request.POST or None,
                   request.FILES or None)
    if form.is_valid():
        album=form.save(commit=False)
        album.cover=request.FILES['cover']
        album.user=request.user
        album.save()
        return render(request,'Yucca/details.html',{'album':album})

    return render(request,'Yucca/add_album.html',{'form':form})


def add_song(request, album_id):
    form=SongForm(request.POST or None,
                  request.FILES or None)
    album=get_object_or_404(Album,pk=album_id)

    if form.is_valid():
        song=form.save(commit=False)
        song.audio=request.FILES['audio']
        song.album=album
        songs= album.song_set.all()
        for s in songs:
            if s.name==song.name:
                context = {'message': 'Song Exists in the Album!',
                           'form':form }
                return render(request,'Yucca/add_song.html', context)

        song.save()
        return render(request,'Yucca/details.html',{'album':album})
    return render(request,'Yucca/add_song.html',{'form':form})


def delete_album(request, album_id):
    album=get_object_or_404(Album, pk=album_id)
    album.delete()
    return redirect ('Yucca:index')

def signup (request):
    form=UserForm(request.POST or None)
    if form.is_valid():
        username=form.cleaned_data['username']
        password=form.cleaned_data['password']
        user=form.save(commit=False)
        user.set_password(password)
        user.save()
        user=authenticate(username=username,password=password)
        login(request, user)
        return redirect('Yucca:index')

    return render(request,'Yucca/signup.html',{'form':form})



def login_user(request):
    if request.method=='POST':
        username=request.POST ['username']
        password=request.POST ['password']
        user=authenticate(username=username,
                          password=password)

        login(request,user)
        return redirect('Yucca:index')
    return render(request,'registration/login.html')

def logout_user(request):
    logout(request)
    return redirect('Yucca:login')

def update_album(request,album_id):
    album = get_object_or_404(Album,pk=album_id)
    form = AlbumForm(request.POST or None,request.FILES or None,instance=album)
    if form.is_valid():
        form.save()
        return redirect('Yucca:index')
    return render(request,'Yucca/add_album.html',{'form':form})


def delete_song(request,album_id,song_id):
    album=get_object_or_404(Album, pk=album_id)
    song=get_object_or_404(Song, pk=song_id)
    song.delete()
    return render(request,'Yucca/details.html',{'album':album})


def update_song(request,album_id,song_id):
    album=get_object_or_404(Album, pk=album_id)
    song=get_object_or_404(Song, pk=song_id)
    form=SongForm(request.POST or None,
                  request.FILES or None,instance=song)


    if form.is_valid():
        form.save()
        return render(request,'Yucca/details.html',{'album':album})
    return render(request, 'Yucca/add_album.html', {'form': form})

Yucca/templates/Yucca/add_album.html
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="panel panel-default" style="background:violet;">
                <div class="panel-body">
                    <h4 class="text-primary" style="font-family:Gloria Hallelujah;">Add Album</h4>
                    <hr>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}
                        <div class="form-group">
                            <button type="submit" class="btn btn-info">SUBMIT</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Yucca/templates/Yucca/add_song.html
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Courgette  ' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Akronim  ' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Shadows Into Light   ' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Kaushan Script ' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Gloria Hallelujah ' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Playball' rel='stylesheet'>

<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="panel panel-default" style="background:Magenta;>
                <div class="panel-body">
                    <h4 class="text-primary"   style="font-family:Gloria Hallelujah;">Add Song</h4>
                    <hr>
                    {% if message %}
                        <div class="alert alert-danger">
                            <h4>{{message}}</h4>
                        </div>
                    {% endif %}
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}
                        <div class="form-group">
                        <button type="submit" class="btn btn-info" style="width:80px;">SUBMIT</button>
                        </div>
                    </form>
                 </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

Yucca/templates/Yucca/details.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

<div class="container" style="background:black;">
    <div class="row">
        <!--Left album infomation-->
        <div class="col-sm-3">
            <div class="panel panel-info" style="background:pink">
                <div class="panel-body">
                    <img src="{{album.cover.url}}" class="img img-thumbnail img-responsive" alt="">
                    <div class="caption">
                        <h5><b><i>{{album.name}}</i></b></h5>
                         <h6>{{album.genre}}</h6>
                    </div>
                </div>

            </div>
        </div>
        <!--End album information-->

        <!--Right Song Information-->
        <div class="col-sm-9">
            <ul class="nav nav-pills" style="background:black">
                <li class="active"><a href="">Songs</a> </li>
                <li><a href="{% url 'Yucca:add-song' album.id %}">Add Song</a>
                </li>
            </ul>
            <div class="panel panel-default" style="margin:3px;background:grey">
                <div class="panel-body">
                    <h4 class="text-primary">All Songs</h4>
                    <table class="table">
                        <tr>
                            <thead>
                            <th>#</th>
                            <th>Song name</th>
                            <th>Audio</th>
                            <th>Favourite</th>
                            <th>Action</th>
                            </thead>
                        </tr>
                        <tbody>
                        {% if album.song_set %}
                            {% for s in album.song_set.all %}
                                <tr>
                                    <td><b>{{s.id}}</b></td>
                                     <td>{{s.name}}</td>
                                    <td>
                                    <a href="{{s.audio.url}}" class="btn btn-info btn-sm" target="_blank">
                                         <i class="fas fa-play-circle"></i>
                                    </a>
                                </td>
                                    <td><a href="" class="btn btn-primary btn sm">
                                        <i class="fas fa-heart"></i>
                                    </a>
                                    <td>
                                        <a href="{% url 'Yucca:update-song' album.id s.id %}" class="btn btn-success btn-sm">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                         <a href="{% url 'Yucca:delete-song' album.id  s.id %}"  onClick='return confirm("Are you sure you want to delete this song?")' class="btn btn-danger btn-sm">

                                             <i class="fas fa-trash"></i>
                                         </a>
                                    </td>

                                </tr>
                            {% endfor %}
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Yucca/templates/Yucca/index.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
<div class="container" style="background:black;">
    <div class="row" >
        {% for album in albums %}
            <div class="col-sm-3">
                <div class="panel panel-default" style="background:violet">
                    <a href="{% url 'Yucca:details' album.id %}">
                        <img src=" {{album.cover.url}}" class="img img-thumbnail" alt="" style="height:200px; width:250px;">
                    </a>

                    <div class="caption" style="margin:3px;">
                        <h5 class="text-primary" style="font-family:Gloria Hallelujah;"><b>{{album.name}}</b></h5>
                         <h6>{{album.artist}}</h6>
                         <a href="{% url 'Yucca:update-album' album.id %}" class="btn btn-primary btn-sm">
                             <i class="fas fa-edit"></i>
                         </a>
                        <a href="" class="btn btn-info btn-sm">
                             <i class="fas fa-heart"></i>
                         </a>
                        <a href="{% url 'Yucca:delete-album' album.id %}" class="btn btn-danger btn-sm" style="float:right;"
                           onClick='return confirm("Are you sure you want to delete this album?")'>
                            <i class="fas fa-trash"></i>
                       </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

Yucca/templates/Yucca/signup.html
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<div class="container">
    <div class="row" >
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <div class="panel panel-default" style="background:turquoise;>
                <div class="panel-body">
                    <h4 class="text-primary">Sign up</h4>
                    <hr>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form|crispy}}
                        <div class="form-group">
                        <button type="submit" class="btn btn-btn-info">SUBMIT</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>